global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'springboot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['springboot-app:8080', 'host.docker.internal:8080']

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node_exporter:9100' ]

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: [ 'mysql_exporter:9104' ]
