package gnu.project.backend.notification.enumerated;

public enum NotificationType {
    RESERVATION_APPROVED,
    RESERVATION_CANCELLED,
    RESERVATION_COMPLETED,
    RESERVATION_REQUEST,
    PAYMENT_REQUIRED,
    PAYMENT_COMPLETED,
    PAYMENT_CANCEL_REQUEST,
    PAYMENT_CANCELED
}
